#!/usr/bin/env python3
"""Build the per-screen static mockups for the v2 reskin.

Static HTML on purpose: no JS, no API, no app.js. These exist to check layout
and iconography against reference-images/ before any of it is committed to
app.js, and they must open over file:// as readily as over a static server.

Icons are read from static-v2/icons.js rather than re-derived here, so the
mockups and the eventual app cannot drift apart: if a slot is remapped, this
regenerates against the same map the application will use.
"""
import json, math, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'datum_sync' / 'static-v2'

ICONS = json.loads(
    re.search(r'export const ICONS = (\{.*?\});',
              (OUT / 'icons.js').read_text(), re.S).group(1))


# The brand mark is inlined rather than <img src>'d so it inherits the dark
# zone's currentColor and still renders over file://. The viewBox is read
# from the file rather than repeated here: it moves whenever the wordmark is
# refitted, and a stale copy would silently crop or letterbox the mark.
_mark = (OUT / 'datum-mark.svg').read_text().strip()
BRAND_VIEWBOX = re.search(r'<svg[^>]*viewBox="([^"]+)"', _mark).group(1)
BRAND_MARK = re.sub(r'^.*?<svg[^>]*>|</svg>\s*$', '', _mark, flags=re.S).strip()


def ico(name, size=17, cls=''):
    if name not in ICONS:
        raise KeyError(f'no icon slot {name!r} — add it to tools/gen_icons.py')
    c = f' class="{cls}"' if cls else ''
    return (f'<svg{c} width="{size}" height="{size}" viewBox="0 0 256 256" '
            f'fill="currentColor" aria-hidden="true">{ICONS[name]}</svg>')


# Sidebar exactly as SECTIONS orders it in app.js, so the mockup can be
# compared against the running v1 without re-sorting anything by eye.
NAV = [
    ('dashboard', 'Dashboard'), ('repositories', 'Repositories'),
    ('automations', 'Automations'), ('notifications', 'Notifications'),
    ('streams', 'Streams'), ('data-virt', 'API endpoints'),
    ('mcp', 'MCP Servers'), ('apps', 'Apps'),
    ('schedules', 'Schedules'), ('jobs', 'Jobs'),
    ('workspaces', 'Workspaces'), ('projects', 'Projects'),
    ('connections', 'Connections'), ('resources', 'Resources'),
    ('analytics', 'Analytics'), ('services', 'Services'),
]
# De-branded only -- "Flow Apps" became "Apps" and nothing moved. Apps is still
# an unimplemented stub, and it overlaps Services, which is the built
# /serve/{name}/ feature already hosting service/static, service/pwa and
# service/dashboard outputs. Whether Apps earns a screen of its own is a
# product question, deliberately left open rather than settled by a rename.
NAV_ADMIN = [
    ('admin', 'Admin'), ('auth-services', 'Authentication Services'),
    ('system-config', 'System Configuration'),
    ('queue-control', 'Queue Control'), ('migration', 'Backup & Restore'),
]


def shell(active, title, body):
    def links(items):
        return '\n'.join(
            f'      <a href="#/{sid}"{" class=\"active\"" if sid == active else ""}>'
            f'{ico(sid)}<span class="nav-label">{label}</span></a>'
            for sid, label in items)

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mock &mdash; {title}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<!-- Generated by tools/gen_mockups.py. Do not hand-edit: regenerate. -->

<div id="app" class="app">
  <div class="brand">
    <button id="nav-toggle" type="button" aria-label="Collapse navigation">
      {ico('nav-toggle', 18)}
    </button>
    <svg class="brand-name brand-mark" height="26" viewBox="{BRAND_VIEWBOX}"
         fill="none" role="img" aria-label="Datum">{BRAND_MARK}</svg>
  </div>

  <header class="topbar">
    <div class="engines" id="engines">{ico('engine', 15)} <b>2</b> engines &middot; <b>0</b> running</div>
    <div class="tb-right">
      <button type="button" class="tb-icon" title="Notifications" aria-label="Notifications">{ico('notifications', 18)}</button>
      <div class="tb-user">
        <button type="button" class="tb-avatar" id="avatar-btn" aria-label="Account menu">MR</button>
      </div>
    </div>
  </header>

  <nav class="sidebar" id="nav" aria-label="Sections">
{links(NAV)}
      <div class="nav-group-label">Admin</div>
{links(NAV_ADMIN)}
      <div class="nav-footer"><b>Datum-Sync</b><br>Workspace runner</div>
  </nav>

  <main class="view" id="view">
{body}
  </main>
</div>

<script src="nav-collapse.js"></script>
<script src="table.js"></script>
</body>
</html>
'''


def action_bar(placeholder, buttons):
    """buttons: list of (label, kind).

    kind is primary/secondary/disabled, or 'one'/'many' for a button table.js
    enables from the selection ('one' = exactly one row, 'many' = one or more).

    Those two render disabled, which is both Flow's initial state and the
    correct state with nothing selected -- so the page is right before any
    script runs, and stays right if table.js never loads. The requirement is
    declared in the markup rather than matched on the label in table.js, so
    renaming a button here cannot silently unwire it.
    """
    out = []
    for label, kind in buttons:
        cls = '' if kind == 'primary' else ' class="secondary"'
        needs = f' data-needs="{kind}"' if kind in ('one', 'many') else ''
        dis = ' disabled' if kind in ('one', 'many', 'disabled') else ''
        out.append(f'        <button type="button"{cls}{needs}{dis}>{label}</button>')
    out.append('        <button type="button" class="secondary icon" '
               f'aria-label="Choose columns">{ico("columns", 16)}</button>')
    return f'''    <div class="action-bar">
      <div class="search">
        <input type="search" placeholder="{placeholder}">
      </div>
      <div class="actions">
        <span class="sel-count" aria-live="polite"></span>
{chr(10).join(out)}
      </div>
    </div>'''


def pager(total, per_page=100):
    """The pre-JS pager, describing what the markup below it actually shows.

    All `total` rows are in the tbody, so the hint says so and all four arrows
    are disabled -- there is no second page until something paginates. table.js
    then slices to `per_page` and rewrites the hint, the arrows and the number
    buttons. Writing "1 to 10 of 12" here instead would be a lie about the
    file: read on its own it lists twelve.

    table.js is a synchronous script at the end of body, so it runs before the
    first paint and the corrected state is the only one ever rendered.
    """
    opts = ''.join(f'<option{" selected" if n == per_page else ""}>{n}</option>'
                   for n in (10, 25, 50, 100))
    return f'''    <div class="pager">
      <div class="pager-btns">
        <button type="button" disabled aria-label="First">{ico('page-first', 14)}</button>
        <button type="button" disabled aria-label="Previous">{ico('page-prev', 14)}</button>
        <button type="button" class="cur">1</button>
        <button type="button" disabled aria-label="Next">{ico('page-next', 14)}</button>
        <button type="button" disabled aria-label="Last">{ico('page-last', 14)}</button>
      </div>
      <div class="pager-right">
        <span class="hint">Showing 1 to {total} of {total} entries</span>
        <div class="pager-per-page">
          <select aria-label="Rows per page">
            {opts}
          </select>
        </div>
      </div>
    </div>'''


# One glyph for both directions: caret-down is caret-up turned over, and
# style.css rotates it on th.sorted.desc. table.js therefore never has to
# build SVG, which would mean shipping icons.js to the browser as well.
ARROW = f'<span class="sort-arrow">{ico("sort-asc", 12)}</span>'


def tabs(items, active):
    return ('    <nav class="page-tabs">\n' + '\n'.join(
        f'      <a href="#"{" class=\"active\"" if t == active else ""}>{t}</a>'
        for t in items) + '\n    </nav>')


# ── screens ──────────────────────────────────────────────────────────────

def screen_repositories():
    rows = [
        ('SCIMAC', 'Geotechnical site plan and report workspaces', 'marcus', 6),
        ('Testing', 'Integration fixtures &mdash; slow, echo_file, chatty, site', 'marcus', 4),
        ('Samples', 'Reference workspaces shipped with the build', 'admin', 3),
    ]
    trs = []
    for name, desc, owner, n in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select {name}"></td>
          <td>
            <div class="cell-name">{ico('repositories', 18)}
              <div>
                <a href="#/repositories/{name}">{name}</a>
                <div class="desc">{desc}</div>
              </div>
            </div>
          </td>
          <td>{owner}</td>
          <td>{n}</td>
          <td><a href="#/repositories/{name}">open</a></td>
        </tr>''')
    body = f'''    <h1>Repositories</h1>

{action_bar('Search repositories by name',
            [('Create', 'primary'), ('Upload', 'secondary'),
             ('Edit', 'one'), ('Remove', 'many')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable sorted" aria-sort="ascending">Repository {ARROW}</th>
          <th class="sortable" aria-sort="none">Owner {ARROW}</th>
          <th class="sortable" aria-sort="none">Workspaces {ARROW}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(len(rows))}'''
    return shell('repositories', 'Repositories', body)


def screen_jobs():
    # Status strings are the API's own, because badge() in app.js uses the raw
    # status as BOTH the class and the label -- inventing "Succeeded" here would
    # style a class that does not exist and read nothing like the real screen.
    # Workspace names are real ones out of repositories/ and carry no extension:
    # a Datum-Sync workspace is a directory holding main.py and manifest.json,
    # not a single file. The ".fmw" these used to show was Flow's, and one of
    # them named a workspace that has never existed here.
    # Twelve rows, not four, because ten of them fit a page and the other two
    # do not. Pagination, and a selection surviving a page change, cannot be
    # demonstrated on a list that never pages -- and a jobs list is the one
    # screen here that really does run long.
    rows = [
        (4821, 'complete', 'SCIMAC', 'site_plan', 'marcus', '12.4s'),
        (4820, 'failed', 'Testing', 'chatty', 'marcus', '3.1s'),
        (4819, 'running', 'Testing', 'echo_file', 'admin', '0.8s'),
        (4818, 'queued', 'Testing', 'slow', 'admin', '&mdash;'),
        (4817, 'complete', 'Testing', 'site', 'admin', '1.9s'),
        (4816, 'complete', 'SCIMAC', 'site_plan', 'marcus', '11.7s'),
        (4815, 'failed', 'Testing', 'echo_file', 'marcus', '0.4s'),
        (4814, 'complete', 'Testing', 'chatty', 'admin', '2.8s'),
        (4813, 'complete', 'Testing', 'slow', 'marcus', '30.2s'),
        (4812, 'complete', 'SCIMAC', 'site_plan', 'admin', '13.0s'),
        (4811, 'failed', 'Testing', 'site', 'marcus', '0.6s'),
        (4810, 'complete', 'Testing', 'echo_file', 'admin', '0.7s'),
    ]
    # Icon per status.
    badge_ico = {'complete': 'ok', 'failed': 'fail',
                 'running': 'run', 'queued': 'pending'}
    trs = []
    for jid, state, repo, ws, who, dur in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select job {jid}"></td>
          <td><a href="#/jobs/{jid}">{jid}</a></td>
          <td><span class="badge {state}">{ico(badge_ico[state], 13)} {state}</span></td>
          <td>
            <div class="cell-name">{ico('workspaces', 18)}
              <div><a href="#/repositories/{repo}/{ws}">{ws}</a>
                <div class="desc">{repo}</div>
              </div>
            </div>
          </td>
          <td>{who}</td>
          <td>{dur}</td>
        </tr>''')
    body = f'''    <h1>Jobs</h1>

{tabs(['Completed', 'Queued', 'Running', 'Dashboards'], 'Completed')}

{action_bar('Search jobs by workspace or user',
            [('Run Workspace', 'primary'), ('Cancel', 'many'),
             ('Remove', 'many')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable sorted desc" aria-sort="descending">Job {ARROW}</th>
          <th class="sortable" aria-sort="none">Status {ARROW}</th>
          <th class="sortable" aria-sort="none">Workspace {ARROW}</th>
          <th class="sortable" aria-sort="none">Requested by {ARROW}</th>
          <th class="sortable" aria-sort="none">Duration {ARROW}</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(len(rows), per_page=10)}'''
    return shell('jobs', 'Jobs', body)


def screen_connections():
    body = f'''    <h1>Connections &amp; Parameters</h1>

{tabs(['Database Connections', 'Web Connections', 'Parameters', 'Tokens'],
      'Database Connections')}

    <h2>Database Connections</h2>
    <p class="page-desc">Database connections store the credentials a workspace
      needs to reach a data source. A workspace refers to one by name, so the
      secret never appears in the workspace itself.</p>

{action_bar('Search connections by name',
            [('Create', 'primary'), ('Duplicate', 'disabled'),
             ('Remove', 'disabled'), ('Manage Database Types', 'secondary')])}

    <div class="empty-state">
      <div class="es-icon">{ico('connections', 48)}</div>
      <h2>No database connections yet</h2>
      <p>Create one to let a workspace reach Postgres, SQL Server or a file
        geodatabase. See <a href="#/resources">Resources</a> for the drivers
        already installed.</p>
      <button type="button">Create Connection</button>
    </div>'''
    return shell('connections', 'Connections', body)


def screen_run_workspace():
    body = f'''    <div class="crumbs">
      <a href="#/repositories">Repositories</a><span>/</span>
      <a href="#/repositories/SCIMAC">SCIMAC</a><span>/</span>
      Run
    </div>

    <div class="page-header">
      <h1>Run Workspace</h1>
      <div class="actions">
        <button type="button" class="secondary">Workspace Actions {ico('dropdown', 13)}</button>
      </div>
    </div>

    <div class="card">
      <h2>Workspace</h2>
      <div class="field">
        <label for="rw-repo">Repository</label>
        <select id="rw-repo">
          <option>SCIMAC</option><option>Testing</option><option>Samples</option>
        </select>
      </div>
      <div class="field">
        <label for="rw-ws">Workspace</label>
        <select id="rw-ws" disabled><option>Select a repository first</option></select>
      </div>
      <div class="field">
        <label for="rw-svc">Service</label>
        <select id="rw-svc" disabled><option>Select a workspace first</option></select>
      </div>
    </div>

    <div class="card">
      <h2>Published Parameters</h2>
      <div class="field">
        <label for="rw-job">Job number <span class="req">*</span></label>
        <input id="rw-job" type="text" placeholder="70023">
      </div>
      <div class="field">
        <label for="rw-buf">Buffer (m)</label>
        <input id="rw-buf" type="number" value="25">
      </div>
      <div class="field check">
        <label><input type="checkbox" checked> Include contours</label>
      </div>
    </div>

    <div class="action-bar">
      <div class="actions">
        <button type="button">{ico('run', 15)} Run</button>
        <button type="button" class="secondary">Cancel</button>
      </div>
    </div>'''
    return shell('jobs', 'Run Workspace', body)


def screen_dashboard():
    """Flow's dashboard geometry over the data v1's screenDashboard already has.

    Every block below except the ring maps 1:1 onto something app.js fetches
    today: tiles, repository cards, a recent-jobs table, the five counters and
    the reference rail. The ring is the exception and is called out in
    STYLE.md -- style.css has carried .ring-chart from the start, Flow draws
    one, and v1 does not, so it is a gap the mockup states rather than hides.
    """
    tiles = [('Run Workspace', 'run'), ('Create Schedule', 'schedules'),
             ('Create Automation', 'automations'), ('Create Connection', 'connections')]

    # Repository cards, not workspace cards. Flow's tile grid is "Last
    # Published Workspaces"; ours is repositories, because that is the unit a
    # Datum-Sync user publishes -- a directory of workspaces, not a file.
    repos = [('SCIMAC', 6), ('Testing', 4), ('Samples', 3), ('Sandbox', 1)]

    recent = [(4821, 'complete', 'SCIMAC/site_plan', '2 minutes ago'),
              (4820, 'failed', 'Testing/chatty', '6 minutes ago'),
              (4819, 'running', 'Testing/echo_file', '7 minutes ago'),
              (4818, 'queued', 'Testing/slow', '7 minutes ago'),
              (4817, 'complete', 'Testing/site', '20 minutes ago')]
    badge_ico = {'complete': 'ok', 'failed': 'fail',
                 'running': 'run', 'queued': 'pending'}

    # Same grouping as COUNTERS in app.js: the three settled states on one
    # row, the two live ones on a wider row beneath. .counter-row's nth-child
    # rules are what set 3-up then 2-up, so the order here is load-bearing.
    counts = {'failed': 18, 'complete': 143, 'cancelled': 2,
              'queued': 1, 'running': 1}
    counters = [[('failed', 'Failed'), ('complete', 'Successful'),
                 ('cancelled', 'Cancelled')],
                [('queued', 'Queued'), ('running', 'Running')]]

    # Ring over the three settled states only -- a queued job has no outcome
    # to colour, and folding it in would make the total drift as work starts.
    # Arithmetic here rather than in the markup so the segments always close:
    # hand-written dasharrays leave a hairline gap the moment a number moves.
    ring = [('complete', counts['complete']), ('failed', counts['failed']),
            ('cancelled', counts['cancelled'])]
    settled = sum(n for _, n in ring)
    circ = 2 * math.pi * 70
    segs, run = [], 0.0
    for state, n in ring:
        length = circ * n / settled
        segs.append(f'        <circle class="{state}" cx="80" cy="80" r="70" fill="none"\n'
                    f'                stroke="currentColor" stroke-width="14"\n'
                    f'                stroke-dasharray="{length:.2f} {circ:.2f}"\n'
                    f'                stroke-dashoffset="{-run:.2f}"></circle>')
        run += length

    body = f'''    <h1>Dashboard</h1>

    <div class="tiles">
{chr(10).join(f'      <a class="tile" href="#/{sid}">{ico(sid, 18)}<span>{label}</span></a>'
              for label, sid in tiles)}
    </div>

    <div class="dash-grid">
      <div class="dash-main">
        <h2>Repositories</h2>
        <div class="ws-cards">
{chr(10).join(f"""          <a class="ws-card" href="#/repositories/{name}">{ico('repositories', 18)}
            <span class="ws-name">{name}</span>
            <span class="ws-meta">{n} workspace{'' if n == 1 else 's'}</span>
          </a>""" for name, n in repos)}
        </div>

        <h2>Recent jobs</h2>
        <table>
          <thead>
            <tr><th>Status</th><th>Workspace</th><th>Submitted</th><th></th></tr>
          </thead>
          <tbody>
{chr(10).join(f"""            <tr>
              <td><span class="badge {st}">{ico(badge_ico[st], 13)} {st}</span></td>
              <td>{ws}</td>
              <td>{ago}</td>
              <td><a href="#/jobs/{jid}">open</a></td>
            </tr>""" for jid, st, ws, ago in recent)}
          </tbody>
        </table>

        <h2>Jobs</h2>
        <div class="counters">
{chr(10).join('          <div class="counter-row">' + ''.join(
    f'<a class="counter {st}" href="#/jobs?status={st}">'
    f'<span class="label">{label}</span><span class="n">{counts[st]}</span></a>'
    for st, label in row) + '</div>' for row in counters)}
        </div>
      </div>

      <div class="dash-rail">
        <div class="rail-card">
          <h3>Job outcomes</h3>
          <div class="ring-chart">
            <svg viewBox="0 0 160 160" role="img"
                 aria-label="{counts['complete']} successful, {counts['failed']} failed, {counts['cancelled']} cancelled">
{chr(10).join(segs)}
            </svg>
            <div class="center">
              <span class="n">{settled}</span>
              <span class="label">Completed</span>
            </div>
          </div>
        </div>

        <div class="rail-card">
          <h3>Reference</h3>
          <a class="link-card" href="/docs">
            <span class="lc-text"><b>REST API</b>
              <span>Every route this page calls, with its schema</span></span>
            <span class="lc-arrow">&rarr;</span>
          </a>
          <a class="link-card" href="#/resources">
            <span class="lc-text"><b>Resources</b>
              <span>Engines, drivers and disk</span></span>
            <span class="lc-arrow">&rarr;</span>
          </a>
        </div>
      </div>
    </div>'''
    # .dashboard scopes the h2 rule -- elsewhere an h2 titles a panel, so
    # without it every heading on this screen renders a size too large.
    return shell('dashboard', 'Dashboard', body).replace(
        'class="view" id="view"', 'class="view dashboard" id="view"')


def screen_schedules():
    # Trigger strings are triggerOf()'s in app.js: a cron expression or a
    # fixed interval, never Flow's "Once a day" prose. Paused schedules show
    # an em-dash for the next run rather than a stale time -- app.js:1227
    # gives the reason, and repeating the display here keeps the mockup
    # honest about a state the real screen has.
    rows = [
        ('nightly-site-plans', 'SCIMAC/site_plan', '0 2 * * *', 'enabled',
         'in 6 hours', '4821'),
        ('hourly-smoke', 'Testing/echo_file', 'every 1h', 'enabled',
         'in 41 minutes', '4819'),
        ('weekly-archive', 'SCIMAC/job_archive', '0 3 * * 1', 'enabled',
         'in 3 days', '4788'),
        ('backup-config', 'Samples/backup', '0 4 * * *', 'paused',
         '&mdash;', '4501'),
    ]
    badge_ico = {'enabled': 'ok', 'paused': 'pending'}
    trs = []
    for name, ws, trig, state, nxt, job in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select {name}"></td>
          <td><span class="badge {state}">{ico(badge_ico[state], 13)} {state}</span></td>
          <td>
            <div class="cell-name">{ico('schedules', 18)}
              <div><a href="#/schedules/{name}">{name}</a>
                <div class="desc">{ws}</div>
              </div>
            </div>
          </td>
          <td><code>{trig}</code></td>
          <td>{nxt}</td>
          <td><a href="#/jobs/{job}">{job}</a></td>
        </tr>''')
    body = f'''    <h1>Schedules</h1>
    <p class="page-desc">A schedule runs one workspace on a cron expression or a
      fixed interval. Pausing one stops it firing without discarding it.</p>

{action_bar('Search schedules by name or workspace',
            [('Create', 'primary'), ('Pause', 'many'),
             ('Edit', 'one'), ('Remove', 'many')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable" aria-sort="none">Status {ARROW}</th>
          <th class="sortable sorted" aria-sort="ascending">Name {ARROW}</th>
          <th class="sortable" aria-sort="none">Trigger {ARROW}</th>
          <th class="sortable" aria-sort="none">Next run {ARROW}</th>
          <th class="sortable" aria-sort="none">Last job {ARROW}</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(len(rows))}'''
    return shell('schedules', 'Schedules', body)


def screen_automations():
    # Flow's own screenshot of this screen is an empty state, but connections
    # already carries that pattern and a second copy locks no new geometry.
    # Populated instead, because the column this screen has and no other does
    # is Last error -- .error is the only place --failed appears as text
    # rather than as a badge, and an empty table would never show it.
    rows = [
        ('publish-site-plans', 'job complete &middot; SCIMAC/site_plan',
         'run workspace', '2 minutes ago', 'enabled', ''),
        ('notify-failures', 'job failed &middot; any repository',
         'webhook', '6 minutes ago', 'enabled',
         'POST https://hooks.internal/notify &rarr; 502'),
        ('nightly-cleanup', 'job complete &middot; Testing/slow',
         'run workspace, webhook', '9 hours ago', 'paused', ''),
    ]
    badge_ico = {'enabled': 'ok', 'paused': 'pending'}
    trs = []
    for name, trig, acts, fired, state, err in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select {name}"></td>
          <td><span class="badge {state}">{ico(badge_ico[state], 13)} {state}</span></td>
          <td>
            <div class="cell-name">{ico('automations', 18)}
              <div><a href="#/automations/{name}">{name}</a>
                <div class="desc">{trig}</div>
              </div>
            </div>
          </td>
          <td>{acts}</td>
          <td>{fired}</td>
          <td class="error">{err}</td>
        </tr>''')
    body = f'''    <h1>Automations</h1>
    <p class="page-desc">An automation watches for finished jobs and runs a
      workspace or calls a URL when one matches.</p>

{action_bar('Search automations by name',
            [('Create', 'primary'), ('Pause', 'many'),
             ('Edit', 'one'), ('Remove', 'many')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable" aria-sort="none">Status {ARROW}</th>
          <th class="sortable sorted" aria-sort="ascending">Name {ARROW}</th>
          <th class="sortable" aria-sort="none">Actions {ARROW}</th>
          <th class="sortable" aria-sort="none">Last fired {ARROW}</th>
          <th class="sortable" aria-sort="none">Last error {ARROW}</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(len(rows))}'''
    return shell('automations', 'Automations', body)


def screen_job():
    # A RUNNING job, deliberately. The progress bar only exists while one is
    # live -- app.js:949 explains that progress is announced and never
    # stored, so it is hidden on load and absent again after a reload. A
    # complete job would leave .progress unrendered and nothing here would
    # pin its geometry. Cancel rather than Resubmit follows for the same
    # reason: showActions() swaps them on the terminal states.
    # .lvl holds the LEVEL, not a timestamp, because that is what the log
    # stream sends -- app.js:1041 builds each line from entry.level and
    # entry.message and there is no time field to render. Timestamps here
    # would look right and lock a column the real screen cannot fill.
    log = [
        ('info', 'job 4819 claimed by engine-2'),
        ('info', 'workspace Testing/echo_file rev 14'),
        ('info', 'reading input: uploads/parcels.gpkg'),
        ('warning', 'attribute "legal_desc" truncated to 255 chars'),
        ('info', 'wrote 1,284 features'),
        ('info', 'progress 62%'),
    ]
    body = f'''    <div class="crumbs">
      <a href="#/jobs">Jobs</a><span>/</span>4819
    </div>

    <div class="page-header">
      <h1>Job 4819</h1>
      <div class="actions">
        <button type="button" class="secondary">{ico('refresh', 15)} Resubmit</button>
        <button type="button" class="danger">Cancel</button>
      </div>
    </div>

    <div class="split">
      <div class="panel">
        <h2>Log</h2>
        <div class="progress">
          <div class="track"><div class="fill" style="width:62%"></div></div>
          <div class="caption"><span>Writing features</span><span>62%</span></div>
        </div>
        <!-- Joined with nothing, and on one line: .log is white-space:
             pre-wrap, so the newline and indent between two <div>s would be
             painted as a blank line each. app.js appends elements with no
             text nodes between them, which is the layout this has to match. -->
        <div class="log">{''.join(
            f'<div class="{lvl}"><span class="lvl">{lvl}</span>{msg}</div>'
            for lvl, msg in log)}</div>
      </div>

      <div class="panel">
        <h2>Details</h2>
        <dl class="kv">
          <dt>Status</dt><dd><span class="badge running">{ico('run', 13)} running</span></dd>
          <dt>Workspace</dt><dd>Testing/echo_file</dd>
          <dt>Requested by</dt><dd>admin</dd>
          <dt>Engine</dt><dd>engine-2</dd>
          <dt>Submitted</dt><dd>10:41:01</dd>
          <dt>Started</dt><dd>10:41:02</dd>
          <dt>Finished</dt><dd>&mdash;</dd>
          <dt>Artifacts</dt><dd>&mdash;</dd>
        </dl>
      </div>
    </div>'''
    return shell('jobs', 'Job 4819', body)


# ── Variations explorer ──────────────────────────────────────────────────
# The only page here that carries JS, and deliberately so: type scale and
# link colour are comparative judgements, and flipping one control on a live
# screen shows far more than a row of static screenshots. It overrides
# tokens on :root only -- it does not fork style.css, so whatever is chosen
# transfers as a one-line edit.

# The first entry of each list is the option now baked into style.css, so the
# page opens on the shipped design and every other radio reads as a departure
# from it. Keep it that way when adding options.

# Contrast measured against white #ffffff (light zone --panel).
LINK_OPTIONS = [
    ('#1D3A5C', 'Navy (shipped)', '11.59:1'),
    ('#0d0d0c', 'Near-black',     '19.44:1'),
    ('#2C5480', 'Navy, lifted',    '7.82:1'),
    ('#6E4E17', 'Amber, deepened', '7.59:1'),
    ('#8A6420', 'Amber, darkened', '5.35:1'),
    ('#C89632', 'Amber',           '2.67:1  FAILS AA'),
]

# Raising the root alone does not get there: at 16px the h1 reaches only
# 24.8px against Flow's ~40, and the row pitch 65 against 78, because
# `h1: 1.55rem` and `td: .75rem` are the binding constraints, not the root.
# So each option bundles root + heading scale + table density.
# Fields: label, root, h1, h2, h3, td padding, note.
TYPE_OPTIONS = [
    ('Flow-matched','16px', '2.5rem',  '1.375rem', '1.125rem','1.15rem','h1 40px, shipped'),
    ('Comfortable', '16px', '2rem',    '1.25rem',  '1.05rem', '1rem',   'h1 32px'),
    ('Root only',   '16px', '1.55rem', '1.1rem',   '.95rem',  '.75rem', 'h1 24.8px'),
    ('Original',    '14px', '1.55rem', '1.1rem',   '.95rem',  '.75rem', 'h1 21.7px'),
]


def screen_variants():
    def radios(name, opts):
        return '\n'.join(
            f'<label><input type="radio" name="{name}" value="{v}"'
            f'{" checked" if i == 0 else ""}><span>{lbl}</span>'
            f'<em>{note}</em></label>'
            for i, (v, lbl, note) in enumerate(opts))

    type_radios = '\n'.join(
        f'<label><input type="radio" name="type" value="{i}"'
        f'{" checked" if i == 0 else ""}><span>{lbl}</span><em>{note}</em></label>'
        for i, (lbl, *_, note) in enumerate(TYPE_OPTIONS))
    type_css = json.dumps([
        f'html,body{{font-size:{r}}} h1{{font-size:{h1}}} h2{{font-size:{h2}}} '
        f'h3{{font-size:{h3}}} td{{padding:{td}}} th{{padding-left:{td};padding-right:{td}}}'
        for _, r, h1, h2, h3, td, _n in TYPE_OPTIONS])

    body = screen_repositories()
    body = body[body.index('<main class="view"'):body.index('</main>') + 7]

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mock &mdash; Variations</title>
<link rel="stylesheet" href="style.css">
<style>
.vbar {{ position: sticky; top: 0; z-index: 9; display: flex; gap: 2.5rem;
  flex-wrap: wrap; padding: 12px 16px; background: #16232F; color: #E8EEF4;
  font: 12px/1.4 system-ui, sans-serif; }}
.vbar section {{ display: flex; gap: .5rem; align-items: center; }}
.vbar h4 {{ margin: 0 .5rem 0 0; font: 600 11px/1 system-ui; letter-spacing: .08em;
  text-transform: uppercase; color: #8FA3B5; }}
.vbar label {{ display: flex; align-items: center; gap: .3rem; cursor: pointer;
  padding: .25rem .45rem; border-radius: 4px; }}
.vbar label:hover {{ background: #1B2C3D; }}
.vbar em {{ font-style: normal; color: #8FA3B5; font-size: 10px; }}
.frame {{ height: calc(100vh - 46px); }}
.frame .app {{ height: 100%; }}
</style>
</head>
<body>

<!-- Generated by tools/gen_mockups.py. Do not hand-edit: regenerate. -->

<div class="vbar">
  <section><h4>Link colour</h4>{radios('link', LINK_OPTIONS)}</section>
  <section><h4>Type scale</h4>{type_radios}</section>
</div>

<div class="frame">
<div id="app" class="app">
  <div class="brand">
    <button type="button" aria-label="Collapse navigation">{ico('nav-toggle', 18)}</button>
    <svg class="brand-name brand-mark" height="26" viewBox="{BRAND_VIEWBOX}"
         fill="none" role="img" aria-label="Datum">{BRAND_MARK}</svg>
  </div>
  <header class="topbar">
    <div class="engines">{ico('engine', 15)} <b>2</b> engines &middot; <b>0</b> running</div>
    <div class="tb-right">
      <button type="button" class="tb-icon" aria-label="Notifications">{ico('notifications', 18)}</button>
      <div class="tb-user"><button type="button" class="tb-avatar">MR</button></div>
    </div>
  </header>
  <nav class="sidebar">
{chr(10).join(f'      <a href="#"{" class=" + chr(34) + "active" + chr(34) if s == "repositories" else ""}>{ico(s)}<span class="nav-label">{l}</span></a>' for s, l in NAV)}
    <div class="nav-group-label">Admin</div>
{chr(10).join(f'      <a href="#">{ico(s)}<span class="nav-label">{l}</span></a>' for s, l in NAV_ADMIN)}
  </nav>
{body}
</div>
</div>

<script>
// Overrides land on :root. --link is redeclared inside .topbar/.view, so a
// :root override alone would lose to that; the light-zone rule is restated
// at higher specificity via a stylesheet rather than an inline style.
const TYPE = {type_css};
const sheet = document.head.appendChild(document.createElement('style'));
function apply() {{
  const link = document.querySelector('[name=link]:checked').value;
  const type = TYPE[document.querySelector('[name=type]:checked').value];
  sheet.textContent = `.topbar, .view {{ --link: ${{link}}; }} ` + type;
}}
document.querySelectorAll('.vbar input').forEach(i =>
    i.addEventListener('change', apply));
apply();
</script>
</body>
</html>
'''


SCREENS = {
    'mock-variants.html': screen_variants,
    'mock-dashboard.html': screen_dashboard,
    'mock-repositories.html': screen_repositories,
    'mock-jobs.html': screen_jobs,
    'mock-job.html': screen_job,
    'mock-schedules.html': screen_schedules,
    'mock-automations.html': screen_automations,
    'mock-connections.html': screen_connections,
    'mock-run-workspace.html': screen_run_workspace,
}


def main():
    for fname, fn in SCREENS.items():
        OUT.joinpath(fname).write_text(fn())
        print('wrote', fname)


if __name__ == '__main__':
    main()
