#!/usr/bin/env python3
"""Build the per-screen static mockups for the v2 reskin.

Static HTML on purpose: no JS, no API, no app.js. These exist to check layout
and iconography against reference-images/ before any of it is committed to
app.js, and they must open over file:// as readily as over a static server.

Icons are read from static-v2/icons.js rather than re-derived here, so the
mockups and the eventual app cannot drift apart: if a slot is remapped, this
regenerates against the same map the application will use.
"""
import json, re, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / 'datum_sync' / 'static-v2'

ICONS = json.loads(
    re.search(r'export const ICONS = (\{.*?\});',
              (OUT / 'icons.js').read_text(), re.S).group(1))


# The brand mark is inlined rather than <img src>'d so it inherits the dark
# zone's currentColor and still renders over file://. The viewBox is read
# from the file rather than repeated here: it moves whenever the wordmark is
# refitted, and a stale copy would silently crop or letterbox the mark.
_mark = (OUT / 'datum-mark.svg').read_text().strip()
BRAND_VIEWBOX = re.search(r'<svg[^>]*viewBox="([^"]+)"', _mark).group(1)
BRAND_MARK = re.sub(r'^.*?<svg[^>]*>|</svg>\s*$', '', _mark, flags=re.S).strip()


def ico(name, size=17, cls=''):
    if name not in ICONS:
        raise KeyError(f'no icon slot {name!r} — add it to tools/gen_icons.py')
    c = f' class="{cls}"' if cls else ''
    return (f'<svg{c} width="{size}" height="{size}" viewBox="0 0 256 256" '
            f'fill="currentColor" aria-hidden="true">{ICONS[name]}</svg>')


# Sidebar exactly as SECTIONS orders it in app.js, so the mockup can be
# compared against the running v1 without re-sorting anything by eye.
NAV = [
    ('dashboard', 'Dashboard'), ('repositories', 'Repositories'),
    ('automations', 'Automations'), ('notifications', 'Notifications'),
    ('streams', 'Streams'), ('data-virt', 'Data Virtualization'),
    ('mcp', 'MCP Servers'), ('flow-apps', 'Flow Apps'),
    ('schedules', 'Schedules'), ('jobs', 'Jobs'),
    ('workspaces', 'Workspaces'), ('projects', 'Projects'),
    ('connections', 'Connections'), ('resources', 'Resources'),
    ('analytics', 'Analytics'), ('services', 'Services'),
]
NAV_ADMIN = [
    ('admin', 'Admin'), ('auth-services', 'Authentication Services'),
    ('system-config', 'System Configuration'),
    ('queue-control', 'Queue Control'), ('migration', 'Backup & Restore'),
]


def shell(active, title, body):
    def links(items):
        return '\n'.join(
            f'      <a href="#/{sid}"{" class=\"active\"" if sid == active else ""}>'
            f'{ico(sid)}<span class="nav-label">{label}</span></a>'
            for sid, label in items)

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Mock &mdash; {title}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>

<!-- Generated by tools/gen_mockups.py. Do not hand-edit: regenerate. -->

<div id="app" class="app">
  <div class="brand">
    <button id="nav-toggle" type="button" aria-label="Collapse navigation">
      {ico('nav-toggle', 18)}
    </button>
    <svg class="brand-name brand-mark" height="26" viewBox="{BRAND_VIEWBOX}"
         fill="none" role="img" aria-label="Datum">{BRAND_MARK}</svg>
  </div>

  <header class="topbar">
    <div class="engines" id="engines">{ico('engine', 15)} <b>2</b> engines &middot; <b>0</b> running</div>
    <div class="tb-right">
      <button type="button" class="tb-icon" title="Notifications" aria-label="Notifications">{ico('notifications', 18)}</button>
      <div class="tb-user">
        <button type="button" class="tb-avatar" id="avatar-btn" aria-label="Account menu">MR</button>
      </div>
    </div>
  </header>

  <nav class="sidebar" id="nav" aria-label="Sections">
{links(NAV)}
      <div class="nav-group-label">Admin</div>
{links(NAV_ADMIN)}
      <div class="nav-footer"><b>Datum-Sync</b><br>Workspace runner</div>
  </nav>

  <main class="view" id="view">
{body}
  </main>
</div>

</body>
</html>
'''


def action_bar(placeholder, buttons):
    """buttons: list of (label, kind) where kind is primary/secondary/disabled."""
    out = []
    for label, kind in buttons:
        cls = '' if kind == 'primary' else ' class="secondary"'
        dis = ' disabled' if kind == 'disabled' else ''
        out.append(f'        <button type="button"{cls}{dis}>{label}</button>')
    out.append('        <button type="button" class="secondary icon" '
               f'aria-label="Choose columns">{ico("columns", 16)}</button>')
    return f'''    <div class="action-bar">
      <div class="search">
        <input type="search" placeholder="{placeholder}">
      </div>
      <div class="actions">
{chr(10).join(out)}
      </div>
    </div>'''


def pager(shown, total, first_last_disabled=True):
    d = ' disabled' if first_last_disabled else ''
    return f'''    <div class="pager">
      <div class="pager-btns">
        <button type="button"{d} aria-label="First">{ico('page-first', 14)}</button>
        <button type="button"{d} aria-label="Previous">{ico('page-prev', 14)}</button>
        <button type="button" class="cur">1</button>
        <button type="button"{d} aria-label="Next">{ico('page-next', 14)}</button>
        <button type="button"{d} aria-label="Last">{ico('page-last', 14)}</button>
      </div>
      <div class="pager-right">
        <span class="hint">Showing 1 to {shown} of {total} entries</span>
        <div class="pager-per-page">
          <select aria-label="Rows per page">
            <option>25</option><option>50</option><option selected>100</option>
          </select>
        </div>
      </div>
    </div>'''


def tabs(items, active):
    return ('    <nav class="page-tabs">\n' + '\n'.join(
        f'      <a href="#"{" class=\"active\"" if t == active else ""}>{t}</a>'
        for t in items) + '\n    </nav>')


# ── screens ──────────────────────────────────────────────────────────────

def screen_repositories():
    rows = [
        ('SCIMAC', 'Geotechnical site plan and report workspaces', 'marcus', 6),
        ('Testing', 'Integration fixtures &mdash; slow, echo_file, chatty, site', 'marcus', 4),
        ('Samples', 'Reference workspaces shipped with the build', 'admin', 3),
    ]
    trs = []
    for name, desc, owner, n in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select {name}"></td>
          <td>
            <div class="cell-name">{ico('repositories', 18)}
              <div>
                <a href="#/repositories/{name}">{name}</a>
                <div class="desc">{desc}</div>
              </div>
            </div>
          </td>
          <td>{owner}</td>
          <td>{n}</td>
          <td><a href="#/repositories/{name}">open</a></td>
        </tr>''')
    body = f'''    <h1>Repositories</h1>

{action_bar('Search repositories by name',
            [('Create', 'primary'), ('Upload', 'secondary'),
             ('Edit', 'disabled'), ('Remove', 'disabled')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable sorted">Repository <span class="sort-arrow">{ico('sort-asc', 12)}</span></th>
          <th>Owner</th>
          <th>Workspaces</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(3, 3)}'''
    return shell('repositories', 'Repositories', body)


def screen_jobs():
    # Status strings are the API's own, because badge() in app.js uses the raw
    # status as BOTH the class and the label -- inventing "Succeeded" here would
    # style a class that does not exist and read nothing like the real screen.
    rows = [
        (4821, 'complete', 'SCIMAC', 'site_plan.fmw', 'marcus', '12.4s'),
        (4820, 'failed', 'SCIMAC', 'soil_log.fmw', 'marcus', '3.1s'),
        (4819, 'running', 'Testing', 'echo_file.fmw', 'admin', '0.8s'),
        (4818, 'queued', 'Testing', 'slow.fmw', 'admin', '&mdash;'),
    ]
    # Icon per status. 'queued' has no .badge rule in style.css at all -- it is
    # rendered here so the omission is visible rather than hypothetical.
    badge_ico = {'complete': 'ok', 'failed': 'fail',
                 'running': 'run', 'queued': 'pending'}
    trs = []
    for jid, state, repo, ws, who, dur in rows:
        trs.append(f'''        <tr>
          <td class="col-check"><input type="checkbox" aria-label="Select job {jid}"></td>
          <td><a href="#/jobs/{jid}">{jid}</a></td>
          <td><span class="badge {state}">{ico(badge_ico[state], 13)} {state}</span></td>
          <td>
            <div class="cell-name">{ico('workspaces', 18)}
              <div><a href="#/repositories/{repo}/{ws}">{ws}</a>
                <div class="desc">{repo}</div>
              </div>
            </div>
          </td>
          <td>{who}</td>
          <td>{dur}</td>
        </tr>''')
    body = f'''    <h1>Jobs</h1>

{tabs(['Completed', 'Queued', 'Running', 'Dashboards'], 'Completed')}

{action_bar('Search jobs by workspace or user',
            [('Run Workspace', 'primary'), ('Cancel', 'disabled'),
             ('Remove', 'disabled')])}

    <table>
      <thead>
        <tr>
          <th class="col-check"><input type="checkbox" aria-label="Select all"></th>
          <th class="sortable sorted">Job <span class="sort-arrow">{ico('sort-desc', 12)}</span></th>
          <th>Status</th>
          <th>Workspace</th>
          <th>Requested by</th>
          <th>Duration</th>
        </tr>
      </thead>
      <tbody>
{chr(10).join(trs)}
      </tbody>
    </table>

{pager(4, 4)}'''
    return shell('jobs', 'Jobs', body)


def screen_connections():
    body = f'''    <h1>Connections &amp; Parameters</h1>

{tabs(['Database Connections', 'Web Connections', 'Parameters', 'Tokens'],
      'Database Connections')}

    <h2>Database Connections</h2>
    <p class="page-desc">Database connections store the credentials a workspace
      needs to reach a data source. A workspace refers to one by name, so the
      secret never appears in the workspace itself.</p>

{action_bar('Search connections by name',
            [('Create', 'primary'), ('Duplicate', 'disabled'),
             ('Remove', 'disabled'), ('Manage Database Types', 'secondary')])}

    <div class="empty-state">
      <div class="es-icon">{ico('connections', 48)}</div>
      <h2>No database connections yet</h2>
      <p>Create one to let a workspace reach Postgres, SQL Server or a file
        geodatabase. See <a href="#/resources">Resources</a> for the drivers
        already installed.</p>
      <button type="button">Create Connection</button>
    </div>'''
    return shell('connections', 'Connections', body)


def screen_run_workspace():
    body = f'''    <div class="crumbs">
      <a href="#/repositories">Repositories</a><span>/</span>
      <a href="#/repositories/SCIMAC">SCIMAC</a><span>/</span>
      Run
    </div>

    <div class="page-header">
      <h1>Run Workspace</h1>
      <div class="actions">
        <button type="button" class="secondary">Workspace Actions {ico('dropdown', 13)}</button>
      </div>
    </div>

    <div class="card">
      <h2>Workspace</h2>
      <div class="field">
        <label for="rw-repo">Repository</label>
        <select id="rw-repo">
          <option>SCIMAC</option><option>Testing</option><option>Samples</option>
        </select>
      </div>
      <div class="field">
        <label for="rw-ws">Workspace</label>
        <select id="rw-ws" disabled><option>Select a repository first</option></select>
      </div>
      <div class="field">
        <label for="rw-svc">Service</label>
        <select id="rw-svc" disabled><option>Select a workspace first</option></select>
      </div>
    </div>

    <div class="card">
      <h2>Published Parameters</h2>
      <div class="field">
        <label for="rw-job">Job number <span class="req">*</span></label>
        <input id="rw-job" type="text" placeholder="70023">
      </div>
      <div class="field">
        <label for="rw-buf">Buffer (m)</label>
        <input id="rw-buf" type="number" value="25">
      </div>
      <div class="field check">
        <label><input type="checkbox" checked> Include contours</label>
      </div>
    </div>

    <div class="action-bar">
      <div class="actions">
        <button type="button">{ico('run', 15)} Run</button>
        <button type="button" class="secondary">Cancel</button>
      </div>
    </div>'''
    return shell('jobs', 'Run Workspace', body)


# ── Variations explorer ──────────────────────────────────────────────────
# The only page here that carries JS, and deliberately so: type scale and
# link colour are comparative judgements, and flipping one control on a live
# screen shows far more than a row of static screenshots. It overrides
# tokens on :root only -- it does not fork style.css, so whatever is chosen
# transfers as a one-line edit.

# The first entry of each list is the option now baked into style.css, so the
# page opens on the shipped design and every other radio reads as a departure
# from it. Keep it that way when adding options.

# Contrast measured against white #ffffff (light zone --panel).
LINK_OPTIONS = [
    ('#1D3A5C', 'Navy (shipped)', '11.59:1'),
    ('#0d0d0c', 'Near-black',     '19.44:1'),
    ('#2C5480', 'Navy, lifted',    '7.82:1'),
    ('#6E4E17', 'Amber, deepened', '7.59:1'),
    ('#8A6420', 'Amber, darkened', '5.35:1'),
    ('#C89632', 'Amber',           '2.67:1  FAILS AA'),
]

# Raising the root alone does not get there: at 16px the h1 reaches only
# 24.8px against Flow's ~40, and the row pitch 65 against 78, because
# `h1: 1.55rem` and `td: .75rem` are the binding constraints, not the root.
# So each option bundles root + heading scale + table density.
# Fields: label, root, h1, h2, h3, td padding, note.
TYPE_OPTIONS = [
    ('Flow-matched','16px', '2.5rem',  '1.375rem', '1.125rem','1.15rem','h1 40px, shipped'),
    ('Comfortable', '16px', '2rem',    '1.25rem',  '1.05rem', '1rem',   'h1 32px'),
    ('Root only',   '16px', '1.55rem', '1.1rem',   '.95rem',  '.75rem', 'h1 24.8px'),
    ('Original',    '14px', '1.55rem', '1.1rem',   '.95rem',  '.75rem', 'h1 21.7px'),
]


def screen_variants():
    def radios(name, opts):
        return '\n'.join(
            f'<label><input type="radio" name="{name}" value="{v}"'
            f'{" checked" if i == 0 else ""}><span>{lbl}</span>'
            f'<em>{note}</em></label>'
            for i, (v, lbl, note) in enumerate(opts))

    type_radios = '\n'.join(
        f'<label><input type="radio" name="type" value="{i}"'
        f'{" checked" if i == 0 else ""}><span>{lbl}</span><em>{note}</em></label>'
        for i, (lbl, *_, note) in enumerate(TYPE_OPTIONS))
    type_css = json.dumps([
        f'html,body{{font-size:{r}}} h1{{font-size:{h1}}} h2{{font-size:{h2}}} '
        f'h3{{font-size:{h3}}} td{{padding:{td}}} th{{padding-left:{td};padding-right:{td}}}'
        for _, r, h1, h2, h3, td, _n in TYPE_OPTIONS])

    body = screen_repositories()
    body = body[body.index('<main class="view"'):body.index('</main>') + 7]

    return f'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Mock &mdash; Variations</title>
<link rel="stylesheet" href="style.css">
<style>
.vbar {{ position: sticky; top: 0; z-index: 9; display: flex; gap: 2.5rem;
  flex-wrap: wrap; padding: 12px 16px; background: #16232F; color: #E8EEF4;
  font: 12px/1.4 system-ui, sans-serif; }}
.vbar section {{ display: flex; gap: .5rem; align-items: center; }}
.vbar h4 {{ margin: 0 .5rem 0 0; font: 600 11px/1 system-ui; letter-spacing: .08em;
  text-transform: uppercase; color: #8FA3B5; }}
.vbar label {{ display: flex; align-items: center; gap: .3rem; cursor: pointer;
  padding: .25rem .45rem; border-radius: 4px; }}
.vbar label:hover {{ background: #1B2C3D; }}
.vbar em {{ font-style: normal; color: #8FA3B5; font-size: 10px; }}
.frame {{ height: calc(100vh - 46px); }}
.frame .app {{ height: 100%; }}
</style>
</head>
<body>

<!-- Generated by tools/gen_mockups.py. Do not hand-edit: regenerate. -->

<div class="vbar">
  <section><h4>Link colour</h4>{radios('link', LINK_OPTIONS)}</section>
  <section><h4>Type scale</h4>{type_radios}</section>
</div>

<div class="frame">
<div id="app" class="app">
  <div class="brand">
    <button type="button" aria-label="Collapse navigation">{ico('nav-toggle', 18)}</button>
    <svg class="brand-name brand-mark" height="26" viewBox="{BRAND_VIEWBOX}"
         fill="none" role="img" aria-label="Datum">{BRAND_MARK}</svg>
  </div>
  <header class="topbar">
    <div class="engines">{ico('engine', 15)} <b>2</b> engines &middot; <b>0</b> running</div>
    <div class="tb-right">
      <button type="button" class="tb-icon" aria-label="Notifications">{ico('notifications', 18)}</button>
      <div class="tb-user"><button type="button" class="tb-avatar">MR</button></div>
    </div>
  </header>
  <nav class="sidebar">
{chr(10).join(f'      <a href="#"{" class=" + chr(34) + "active" + chr(34) if s == "repositories" else ""}>{ico(s)}<span class="nav-label">{l}</span></a>' for s, l in NAV)}
    <div class="nav-group-label">Admin</div>
{chr(10).join(f'      <a href="#">{ico(s)}<span class="nav-label">{l}</span></a>' for s, l in NAV_ADMIN)}
  </nav>
{body}
</div>
</div>

<script>
// Overrides land on :root. --link is redeclared inside .topbar/.view, so a
// :root override alone would lose to that; the light-zone rule is restated
// at higher specificity via a stylesheet rather than an inline style.
const TYPE = {type_css};
const sheet = document.head.appendChild(document.createElement('style'));
function apply() {{
  const link = document.querySelector('[name=link]:checked').value;
  const type = TYPE[document.querySelector('[name=type]:checked').value];
  sheet.textContent = `.topbar, .view {{ --link: ${{link}}; }} ` + type;
}}
document.querySelectorAll('.vbar input').forEach(i =>
    i.addEventListener('change', apply));
apply();
</script>
</body>
</html>
'''


SCREENS = {
    'mock-variants.html': screen_variants,
    'mock-repositories.html': screen_repositories,
    'mock-jobs.html': screen_jobs,
    'mock-connections.html': screen_connections,
    'mock-run-workspace.html': screen_run_workspace,
}


def main():
    for fname, fn in SCREENS.items():
        OUT.joinpath(fname).write_text(fn())
        print('wrote', fname)


if __name__ == '__main__':
    main()
